### ISSUE TITLE
Awaited short-URL hidden by Discord

### ISSUE THREAD

**Issue by ddugovic** [typpo/quickchart-js#32]
I don't know why, but images with dozens of data points do not display in Discord.  However, if I log those (properly awaited) short URLs to a file then seconds later manually paste that URL into Discord, then chart images do show.  Should I force my app to download charts to verify whether short URLs are invalid?

I don't have a SSCCE, just https://github.com/ddugovic/lishogi-discord (which empowers players to graph their 60-day rating history with the !profile command).

**Comment by typpo** [comment]
This is happening because short URLs are not immediately active.  The store is eventually consistent and it can take "up to" a minute for short URLs to propagate globally, though in practice it's usually a second or two.  This is why sometimes Discord can't immediately crawl short URLs, but when you wait a few seconds they become active and Discord can crawl them.

**Comment by ddugovic** [comment]
Ah, OK, thanks for the clarification.
